[package]
name = "syn-scan-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.33.0"
rand = "0.8.5"
pnet_packet = "0.33.0"